{{- include "bjw-s.common.loader.init" . -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bjw-s.common.lib.chart.names.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
