---

# Project information
site_name: seanv | Helm charts | Docs
site_description: Docs for the seanv Helm charts repository
site_author: seanv
site_url: https://osnabrugge.github.io/helm-charts/docs

# Repository
repo_name: osnabrugge/helm-charts
repo_url: https://github.com/osnabrugge/helm-charts
edit_uri: ""

# Configuration
theme:
  name: mkdocs
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: mkdocs/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: mkdocs/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

docs_dir: ../../docs
site_dir: ../../_site

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/osnabrugge
    - icon: fontawesome/brands/discord
      link: https://discord.gg/k8s-at-home

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
