---
apiVersion: v2
appVersion: v4.0.1
description: multus CNI allows multiple NICs per pod
name: multus
version: 4.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - multus
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/multus
icon: https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/docs/images/Multus.png
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
maintainers:
  - name: Sean
    email: sean@seanv.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Updating to support new installation method for v4
