# See https://pre-commit.com for more information
exclude: |
  (?x)^(
    .github\/actions\/.*\/dist\/.*
  )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: check-case-conflict

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
  hooks:
  - id: remove-crlf
  - id: remove-tabs

- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
    - id: helm-docs-built
      #entry: ./.deps/helm-docs/helm-docs "${@}"
      args:
        # Set log level
        - --log-level=info

        # Make the tool search for charts only under the `example-charts` directory
        - --chart-search-root=charts

        # The `./` makes it relative to the chart-search-root set above
        - --template-files=./../.ci/helm-docs/README.md.gotmpl

        # Repeating the flag adds this to the list
        # A base filename makes it relative to each chart directory found
        - --template-files=README_CONFIG.md.gotmpl
